const List<Map<String, dynamic>> languageList = [
  {'name': 'English', 'localName': 'English'},
  {'name': 'Amharic', 'localName': 'አማርኛ'},
  {'name': 'Oromoo', 'localName': 'Oromo'},
  {'name': 'Albanian', 'localName': 'Shqip'},
  {'name': 'Arabic', 'localName': 'العربية'},
  {'name': 'English 2', 'localName': 'English'},
  {'name': 'Amharic 2', 'localName': 'አማርኛ'},
  {'name': 'Oromoo 2', 'localName': 'Oromo'},
  {'name': 'Albanian 2', 'localName': 'Shqip'},
  {'name': 'Arabic 2', 'localName': 'العربية'},
  // {'name': 'English', 'localName': 'English'},
  // {'name': 'English', 'localName': 'English'},
  // {'name': 'English', 'localName': 'English'},
  // {'name': 'English', 'localName': 'English'},
  // {'name': 'English', 'localName': 'English'},

  // 'Amharic': 'አማርኛ',
  // 'Oromoo': 'Oromo',
  // 'Afrikaans': 'Afrikaans',
  // 'Albanian': 'Shqip',
  // 'العربية': 'Arabic',
  // 'English2': 'English',
  // 'Amharic2': 'አማርኛ',
  // 'Oromoo2': 'Oromo',
  // 'Afrikaans2': 'Afrikaans',
  // 'AlbanianShqip2': 'Shqip2',
  // 'Arabic': 'العربية2'
];
