// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOUXM7QeW4sQqj5tzo0jVjpHbXIVN-j4',
    appId: '1:1072557538193:web:b5fa9caa2a933effb43830',
    messagingSenderId: '1072557538193',
    projectId: 'whatsapp-clone-backend-ba6fe',
    authDomain: 'whatsapp-clone-backend-ba6fe.firebaseapp.com',
    storageBucket: 'whatsapp-clone-backend-ba6fe.appspot.com',
    measurementId: 'G-3TGYCQ2352',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6hIJm7BH5A_ti5qTQ_9pH3iUpsguNeIQ',
    appId: '1:1072557538193:android:58ef53c1642c0a97b43830',
    messagingSenderId: '1072557538193',
    projectId: 'whatsapp-clone-backend-ba6fe',
    storageBucket: 'whatsapp-clone-backend-ba6fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf051X3ezWXhTmdMgX0SbM3iUhZ2UxB8Y',
    appId: '1:1072557538193:ios:5c0855a00cf928cdb43830',
    messagingSenderId: '1072557538193',
    projectId: 'whatsapp-clone-backend-ba6fe',
    storageBucket: 'whatsapp-clone-backend-ba6fe.appspot.com',
    iosBundleId: 'com.example.flutterWhatsappCloneWithFirebase',
  );
}
